### ISSUE TITLE
Bower, distribution, minified version and more

### ISSUE THREAD

**Issue by mrmlnc** [drKraken/notification-fallback.js#1]
Please add the ability to install a package using the [Bower](http://bower.io/). How to do it:

 * [Create `bower.json` file](http://bower.io/docs/creating-packages/#bowerjson). 
 * [Register this package](http://bower.io/docs/creating-packages/#register).

The Proposal:

 * Create the distribution directory `dist/` and move the file there `notification.js`.
 * Create minified version for `notification.js` file in `dist/`.
 * Add a description of the change notification CSS-styles.
 * Use the default style notification (icon, title, text). For example, to base the design of Google Chrome.
 * Add the ability to add icons.

Anyway, thanks for the work!

**Comment by drKraken** [comment]
Thanks for advice, i will add installing via bower, compressed version and ability to add icon today.
Also PR are welcome.
